### ISSUE TITLE
 google.api_core.exceptions.ServiceUnavailable: 503 POST under high traffic condition

### ISSUE THREAD

**Issue by supreme-core** [googleapis/python-storage#1060]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-storage/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Ubuntu 20
  - Python version: `python --3.8`
  - pip version: `pip --3.8`
  - `google-cloud-storage` version: `2.7.0`

#### Steps to reproduce
Encountered exception: google.api_core.exceptions.ServiceUnavailable: 503 POST under high traffic condition

I am doing performance test to reproduce an exception we are seeing in our development environment. The exception is thrown when copying blobs. There are about 500 blobs to copy over, with each blob of about 2MB, no file exceeds 6MB. The copy operation is to copy over a blob from one bucket to another bucket using copy_blobs() method. Once everything copied over, I proceed to delete the blobs from the target bucket. Then, repeat the process again in a loop. The loop runs about 11 times. 

In my test, the exception is throw roughly on the sixth iteration when copying blobs over. So each loop it would copy over 500 blobs each about 2MB, total a size of 1GB. Is there a restriction on the amount of traffic allow within a given timeframe? For example, nothing over 6GB within 3min? 
  
#### Code example

```python
```

#### Stack trace
```
# example
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by supreme-core** [comment]
That make sense. 

Why aren't retry the default option? I assume that would be the sensible thing to do if there are a chance of having network hiccups.

Does the retry applicable to all errors? or specific ones?
What is the difference between types of retries? Is there any more documentation I can read up to understand it?

**Comment by BenWhitehead** [comment]
Great, I'm glad I understood correctly!

> Why aren't retry the default option? I assume that would be the sensible thing to do if there is chance of having network hiccups.

In GCS writes require extra request metadata in order to make them idempotent, and therefor safe to retry. We use Request Preconditions[1] to accomplish this. These request preconditions[2] you can think of as being in the same vein as compare-and-set operations in programming languages.

For example, when writing to GCS if there isn't any precondition the request will overwrite anything that may already be present.

If we add `if_generation_match=0`, that effectively tells GCS "Only create the new object if one of the same name does not already exist"

> Does the retry applicable to all errors? or specific ones?
> What is the difference between types of retries? Is there any more documentation I can read up to understand it?

There are specific categories of request failures which are considered retryable.

For the python library specifically the list of retryable failures are outlined in https://cloud.google.com/storage/docs/retry-strategy#python Those docs go into detail about which operations are conditionally idempotent, status code and client retry config options. It's a great source for getting familiar with retries in GCS.


[1] https://cloud.google.com/storage/docs/request-preconditions
[2] https://cloud.google.com/storage/docs/retry-strategy#idempotency

**Comment by supreme-core** [comment]
One last question before I close this issue.

What is "generation match" and "meta generation match"?

**Comment by BenWhitehead** [comment]
All Objects in GCS have a `generation` and a `metageneration`[1]. The `generation` is the unique number associated with the bytes of the Object, while the `metageneration` is the unique number associated with the Metadata of the Object[2].

When you create an Object, the metadata of that Object (`name`, `Content-*` headers, create time, etc) with receive a `metageneration` while the actual bytes of the object (even if empty) will receive a `generation`. These values can then be used in the preconditions `ifGeneration{Not,}Match` and `ifMetageneration_{Not,}Match` when issuing a request. 

For example when updating the bytes of an Object, you generally want to constrain the update against the known current `generation` of the object. Whereas when updating the metadata of an Object, you will want to constrain the update against the current `metageneration`.

[1] https://cloud.google.com/storage/docs/metadata#generation-number
[2] https://cloud.google.com/storage/docs/metadata
[3] https://cloud.google.com/storage/docs/request-preconditions#precondition_criteria

**Comment by supreme-core** [comment]
Many thanks!
