### ISSUE TITLE
Typo in clear_lifecycle_rules function

### ISSUE THREAD

**Issue by mxdlx** [googleapis/python-storage#1074]
This is just a typo, the function name is `clear_lifecyle_rules` when it should be `clear_lifecycle_rules`. Here's the permalink: https://github.com/googleapis/python-storage/blob/13f6d2115f600a65fa534fa9b175e23486e51ba5/google/cloud/storage/bucket.py#L2280

**Comment by andrewsg** [comment]
Yep, sure is. I can't believe no one commented on this in the five years this code has been live. Thank you for letting us know.

Since people may have written code that uses the misspelled function, I will recommend fixing the typo but adding an alias for the misspelling, perhaps with a DeprecatingWarning and plan to remove it in a future version (optional).
