### ISSUE TITLE
Transaction guarantee and rollback

### ISSUE THREAD

**Issue by supreme-core** [googleapis/python-storage#1080]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**

Hi,

Please confirm if there's a transaction guarantee with batch operation. Like a transaction scope block to allow multiple deletion of blobs. If any of the deletion fails, previous execution will rollback its state. 
If there is, where can I look up the usage?
If it is not available, is it possible in future release?

 **Describe the solution you'd like**

```python 
blobs = bucket.list_blobs(prefix="folder_name")
with transaction_block:
   for b in blobs:
      # if any of the delete fails, previous deletion cancels
       b.delete()
```

 **Describe alternatives you've considered**
 **Additional context**

**Comment by cojenco** [comment]
Hi @supreme-core there is no transaction guarantee with batch operations. The sub-requests contained in batch operations perform regardless of previous sub-request succeeding or failing. 

You’ll receive a 400 error if the overall batch request isn't formatted correctly or Cloud Storage is unable to parse it into sub-requests. Otherwise, Cloud Storage returns a 200 status code, even if some or all of the sub-requests fail. See [official docs](https://cloud.google.com/storage/docs/batch) for more details.

The python client has limited Batch support, as documented [here](https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.batch), and we don't have this on our roadmap as of right now.

**Comment by supreme-core** [comment]
Thanks for the info!
