### ISSUE TITLE
Regression in public_url and incorrectly encoding / as %2F

### ISSUE THREAD

**Issue by frankyn** [googleapis/python-storage#109]
Raised in #3809, and raising a new bug. blob.public_url returns a URL that encodes /. This was originally fixed in #3809, but there is now a regression.

@IlyaFaer could you pick up this fix?

Thank you.

**Comment by IlyaFaer** [comment]
@frankyn, sure, taking a look

**Comment by IlyaFaer** [comment]
Hello @atteneder, speaking about [your comment](https://github.com/googleapis/google-cloud-python/issues/3809#issuecomment-613902760)

I suppose, the problem here is in version. `gcloud 0.18.3` seems to be [released](https://pypi.org/project/gcloud/0.18.3/) in 2016, while [the fix](https://github.com/googleapis/google-cloud-python/pull/4716) for slash escaping was made in 2018.

In `gcloud 0.18.3` I see this old code:
```python
return '{storage_base_url}/{bucket_name}/{quoted_name}'.format(
            storage_base_url='https://storage.googleapis.com',
            bucket_name=self.bucket.name,
            quoted_name=quote(self.name, safe=''))
```
In which the default `safe="/"` is overriden to `''`.

I've tried to get URLs in my Storage version (`google-cloud-storage 1.21.0`), it seems to be working correctly:

![Безымянный2](https://user-images.githubusercontent.com/26030071/79441300-ba677b80-7fdf-11ea-8d92-7f936901ca80.png)

So, I'd advice to upgrade your Storage libs. You can put `"/"` into `safe` manually as well, in case if upgrading can cause any troubles.

**Comment by atteneder** [comment]
Hi,

thanks a lot for the hint!

I totally didn't read carefully enough that gcloud was replaced by google-cloud which was replaced by google-cloud-*

Will test soon, but I guess it's safe to say this can be closed.

Thanks a lot!

**Comment by frankyn** [comment]
Ah, thanks @IlyaFaer, for I got confused with / encoding versus spaces. 

The latest library does support this as expected. Thanks for getting this unblocked!
