### ISSUE TITLE
ImportError in Google Cloud Function: cannot import name 'storage' from 'google.cloud'

### ISSUE THREAD

**Issue by rammady** [googleapis/python-storage#1099]
I've been working on a Google Cloud Function that reads GCP log files and stores them in a bucket. It's written in Python and is deployed via the Google Cloud Console.

1# Here is the main structure of my function located in the main.py:

`
import base64
import json
import os
import uuid
from tempfile import NamedTemporaryFile
from google.cloud import storage

// Global variables
BATCH_SIZE = 10  # Number of log entries to write to GCS at once
current_batch_size = 0
tmp_file = NamedTemporaryFile(mode='w', delete=False)

// Function definition
def logs_to_gcs(data, context):
    global current_batch_size, tmp_file
    # Processing and storing log entries
    # ...

 // I'm skipping the rest for brevity, but the full function processes logs, writes them to a CSV and uploads it to a GCS bucket.

`

2# I have specified the google-cloud-storage library as a dependency in my requirements.txt file:
`google-cloud-storage>=1.42.0
`

3# However, when I run the function from the Google Cloud Console, I receive the following ImportError:

`ImportError: cannot import name 'storage' from 'google.cloud' (unknown location)
`

The error seems to occur at the import statement in the main.py script:

`from google.cloud import storage
`
I'm using the Python 3.10 runtime and I've made sure that the requirements.txt file is in the correct location. I've been trying to troubleshoot this issue for a while now but I haven't been able to find a solution.

Has anyone encountered a similar issue and could possibly suggest a solution? Is this a compatibility issue with Python 3.10, or is there a problem with the way I've set up my requirements.txt file or the import statement in the script? Any advice would be much appreciated.

**Comment by parthea** [comment]
Hi @rammady,

I'm going to transfer this issue to the repository for `google-cloud-storage` as this issue is related to the client for Google Cloud Storage.

**Comment by rmaddheshiya** [comment]
Thank you @parthea

**Comment by andrewsg** [comment]
This looks at first glance to be an issue with usage of Cloud Functions, and not a client library bug per se, but we can try to diagnose it.

First, do any other libraries you're installing with requirements.txt work, or are they all broken in the same way?

Second, do you have any files or directories in your own function named "google", "cloud" or "storage"? (with or without ".py")

Third, if you add random characters to your requirements.txt file, do you get a different error (because it reads the requirements file and fails to process the random package name) or do you get the same error (indicating the requirements file is not even being looked at)?

**Comment by rmaddheshiya** [comment]
Hi Andrew,
Thank you for your response. Before providing answer to your questions I would like to provide little more information because I feel this is related to your questions.
I'm deploying GCP cloud function directly on the GCP console and I'm not executing cloud function from my location machine.

Answers to you questions:
1# First, do any other libraries you're installing with requirements.txt work, or are they all broken in the same way?

**My answer:** 
In GCP function I've only 2 files 
 [i]  main.py
 [ii] requirements.txt (This file contains only one line which is "google-cloud-storage>=2.10.0")
 
 **2#** Second, do you have any files or directories in your own function named "google", "cloud" or "storage"? (with or without ".py")
 
 **My answer:** No , I don't have any files or directories in your own function named "google", "cloud" or "storage"? (with or without ".py")
 
 **3#** 
 
Third, if you add random characters to your requirements.txt file, do you get a different error (because it reads the requirements file and fails to process the random package name) or do you get the same error (indicating the requirements file is not even being looked at)?

 **My answer:** 
 
 I tried this , I put "t" in the requirements.txt file just below the line "cloud" and earlier function was getting deployed successfully with the error that I shared in the main(first) thread of this conversation but this time function failed with below error. Please suggest and guide. Please let me know if you need more information.
 
 {
insertId: "-tgm58d1f8m"
logName: "projects/suki-dev/logs/cloudaudit.googleapis.com%2Factivity"
operation: {
id: "operations/c3VraS1kZXYvdXMtY2VudHJhbDEvbG9nc190b19nY3MvWW9EOXJyUWhramc"
last: true
producer: "cloudfunctions.googleapis.com"
}
protoPayload: {
@type: "type.googleapis.com/google.cloud.audit.AuditLog"
status: {
code: 3
message: "Build failed: Collecting google-cloud-storage>=2.10.0 (from -r requirements.txt (line 1))
  Downloading google_cloud_storage-2.10.0-py2.py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.6/114.6 kB 4.7 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement t (from versions: none)
ERROR: No matching distribution found for t; Error ID: 656dd225"
}
authenticationInfo: {1}
serviceName: "cloudfunctions.googleapis.com"
methodName: "google.cloud.functions.v1.CloudFunctionsService.UpdateFunction"
resourceName: "projects/suki-dev/locations/us-central1/functions/logs_to_gcs"
}
receiveTimestamp: "2023-08-06T07:54:03.238406827Z"
resource: {2}
severity: "ERROR"
timestamp: "2023-08-06T07:54:02.482092Z"
}

**Comment by andrewsg** [comment]
Hmm, that's interesting. So the requirements file is being read and the package is being installed.

What exact method are you following to run the function and how are you inspecting the logs to find the stack trace that you shared earlier?

**Comment by rmaddheshiya** [comment]
Hi Andrew ,
Sorry for late reply. 
I'm using GCP console to run my function manually and for logs I'm using Logs Explorer.

**Comment by andrewsg** [comment]
Thanks. I am afraid I'm at the limit of my Cloud Functions expertise personally, so I will have to refer you to Cloud Functions support, which you can access through the question mark icon in GCP Console. At the moment, I don't see any evidence that this an issue with the client library and since we've ruled out some of the most straightforward possible reasons (package not being installed, running the function wrong from the command line) I don't have the specialized knowledge to diagnose the issue. I hope you can find a resolution with support soon.

**Comment by rajkkooapp** [comment]
Hey @andrewsg , facing the same issue while creating custom spark image on dataproc, following is the docker file for reproduciblity. 

**Error**
``` from google.cloud import storage
ImportError: cannot import name 'storage' from 'google.cloud' (unknown location)
```

**DockerFile**
```FROM asia-south1-docker.pkg.dev/cloud-dataproc/spark/dataproc_2.0:latest

# Change to root temporarily so that it has permissions to create dirs and copy files.
USER root

# Install Google Cloud SDK
RUN curl -sSL https://sdk.cloud.google.com/ | bash

ENV PATH $PATH:/root/google-cloud-sdk/bin

# Combine pip installations
RUN pip3 install --upgrade \
    boto3 requests numpy pandas scikit-learn slack-sdk datasets emoji \
    sentence-transformers gcloud  google-cloud google-cloud-secret-manager google-cloud-storage && \
    rm -rf /root/.cache/pip  # Clean pip cache to reduce size


# AWS ENV VARIABLES
ENV AWS_REGION=ap-south-1
```

Following are observations based on the investigations I've done in past few hours:
Dataproc base image python version is 3.8 while google-cloud-storage version which gets installed has 3.9 in its name:

```google_cloud_core-2.3.3-py3.9-nspkg.pth
google_cloud_core-2.3.3.dist-info
google_cloud_secret_manager-2.16.3-py3.9-nspkg.pth
google_cloud_secret_manager-2.16.3.dist-info
google_cloud_storage-2.10.0-py3.9-nspkg.pth
google_cloud_storage-2.10.0.dist-info 
```

**Comment by rajkkooapp** [comment]
Hey @andrewsg, thanks for your response. For some reason, the GCR Artifact Registry docker latest tag wasn't working, I pointed the image to a specific version and it worked. Yet to figure out why the latest tag isn't working.

**Comment by andrewsg** [comment]
Okay, thanks @rajkkooapp. 

@rmaddheshiya @rammady hopefully this is related to your original problem; if it is not and the problem persists, please let me know.

**Comment by danny12344** [comment]
I'm having the same issue as @rmaddheshiya did you ever get this solved?

**Comment by michal-wojtanis-solwit** [comment]
I also have this problem @rammady did You got this solved?

**Comment by andrewsg** [comment]
@danny12344 @michal-wojtanis-solwit All problems of this category should have something to do with package installation and the environment, and not the package itself. Please verify that the method you are using to install packages and import them into your application works in general.
