### ISSUE TITLE
A weird behavior when uploading files

### ISSUE THREAD

**Issue by rfan-debug** [googleapis/python-storage#1203]
#### Environment details

  - OS type and version: `OS X Sonoma 14.2`
  - Python version: `python --version`, pip version: `pip --version`
   ```
   Python 3.10.9
   pip 23.1.2
   ```
  - `google-cloud-storage` version: `pip show google-cloud-storage`
   ```
  Name: google-cloud-storage
  Version: 2.13.0
  Summary: Google Cloud Storage API client library
  Home-page: https://github.com/googleapis/python-storage
  Author: Google LLC
  Author-email: googleapis-packages@google.com
  License: Apache 2.0
  Requires: google-api-core, google-auth, google-cloud-core, google-crc32c, google-resumable-media, requests
  Required-by: gcsfs, google-cloud-aiplatform, kfp, treat-bsl
   ```

#### Steps to reproduce

Run the following code. 

#### Code example

```python
from google.cloud.storage import Client
gcs_client = Client()
bucket = gcs_client.bucket("your-bucket")
blob = bucket.blob("test_path")
blob.upload_from_filename("./eval.py")
```
This code will copy ./eval.py to `gs://your-bucket/test_path`, hereby the `gs://your-bucket/test_path` is a file.

--------------
```python
from google.cloud.storage import Client
gcs_client = Client()
bucket = gcs_client.bucket("your-bucket")
blob = bucket.blob("test_path/")
blob.upload_from_filename("./eval.py")
```

This code will create an EMPTY folder: `gs://your-bucket/test_path/` but does not upload the file at all. However, a similar command in terminal, `gsutil cp ./eval.py gs://your-bucket/test_path/`, will copy the file to `gs://your-bucket/test_path/eval.py`. The python lib's behaviors seems to be very anti-intuitive to me.  

Should this behavior be considered as a bug?

**Comment by andrewsg** [comment]
GCS does not have a concept of "folders" - an object that ends in "/" is a valid object name, not a container. "gsutil cp" may mask this in some cases in order to emulate a filesystem operation, but the client libraries are intended to be intentional and specific about object names in a way that "gsutil cp" is not, in order to be predictable in handling programmatically generated or user input generated object names.

In your example you will find that rather than an empty folder, an actual object called test_path/ is created with the correct contents of ./eval.py. This is working as intended. `upload_from_filename` only consumes data from the file specified, it isn't intended to automatically concatenate the filename with the object name.
