### ISSUE TITLE
Datastore emulator causes cloud storage client to hang

### ISSUE THREAD

**Issue by pb-jeff-oneill** [googleapis/python-storage#1284]
#### Environment details

  - OS type and version: Mac 14.5
  - Python version: 3.11.4
  - pip version: 24.0
  - `google-cloud-storage` version: 2.11.0 and 2.16.0 (tried both)

#### Steps to reproduce

Steps to reproduce:

This problem started around June 1. Before, I have been doing this for several years without any issues.

The problem is that `storage.Client()` freezes and it is caused by some interaction with running the cloud datastore emulator locally. This happens with either the older emulator (`gcloud beta emulators datastore start`) or the newer one (`gcloud emulators firestore start`). I have tried downgrading `gcloud` and two versions of `google-cloud-storage` listed above.

Run the script below. At `storage.Client()`, the script hangs indefinitely with no output. You can't even ctrl-c to stop the script. You need to kill -9 in a separate terminal window.

If you comment out the three lines starting with `with datastore_client.context():`, then `storage.Client()` works.

Since the code just freezes, I am at a loss as to how to debug.

#### Code example

```
import os
from google.cloud import ndb, storage

print('starting')

class User(ndb.Model):
    email = ndb.StringProperty(required=True)

os.environ['DATASTORE_DATASET'] = 'my-project'
os.environ['DATASTORE_EMULATOR_HOST'] = 'localhost:8081'
os.environ['DATASTORE_EMULATOR_HOST_PATH'] = 'localhost:8081/datastore'
os.environ['DATASTORE_HOST'] = 'http://localhost:8081'
os.environ['DATASTORE_PROJECT_ID']= 'my-project'

datastore_client = ndb.Client('my-project')

email = 'me@example.com'

with datastore_client.context():
    user = User.get_by_id(email)
    print(user)

# This hangs and you can't even ctrl-c to stop.
# Works if datastore client stuff is commented out.
storage_client = storage.Client('patent-claim')
print('done')
```

**Comment by pb-jeff-oneill** [comment]
It seems to be IPv4/IPv6 related because changing from `localhost` to `127.0.0.1` fixes it.

What ever the cause, it seems that it shouldn't cause `storage.Client()` to hang.

**Comment by cojenco** [comment]
Hi @pb-jeff-oneill I dug around, and this seems to be a known issue in the firebase emulator where localhost sometimes resolves to an IPv6 address and doesn't connect properly. In this case, the storage client is not at fault. When this happens in the firebase emulator, subsequent request hangs. 

The firebase emulator team has therefore updated documentation with recommendations to use `127.0.0.1` instead of `localhost`. See https://cloud.google.com/firestore/docs/emulator  and https://github.com/firebase/firebase-tools/issues/6462#issuecomment-1777694854 for more information.

Closing this issue. If you have further questions, feel free to raise in the [firebase tools](https://github.com/firebase/firebase-tools) repository.
