### ISSUE TITLE
Async Storage Client

### ISSUE THREAD

**Issue by Munna0912t** [googleapis/python-storage#1366]
Async functions are very crucial to use `GCS` APIs in production.

There is neither any `async client` for google cloud storage nor any async function for upload/download blob.

There is an open issue for the same since last 3 years, but still not provided and async client. please look into it on high priority. 
https://github.com/googleapis/python-storage/issues/478

Looking forward for the support, please provide this feature.

**Comment by andrewsg** [comment]
Thank you for your input. We are looking at async interface options, but due to the scale of the change (probably a full rewrite of the library) we need help scoping the project. Can you please comment to the original bug, which you've linked, with some details on your use case for async and what parts of the library in particular you need to use asynchronously? Thank you.

**Comment by Munna0912t** [comment]
@andrewsg I am uploading some audio files (10-100 MBs) to GCS and need gcs uri to get transcription for the video. I want that while the data is being uploaded it doesn't block the thread at my async endpoint. 
So I need blob.async_upload_from_file() methods.
