### ISSUE TITLE
requests is missing as dependency

### ISSUE THREAD

**Issue by simonvanderveldt** [googleapis/python-storage#268]
`requests` is used directly by several modules in this project, see https://github.com/googleapis/python-storage/search?l=Python&q=requests yet it's not listed in `setup.py` in `install_requires`.

(note that this won't be an issue for most people because `requests` is pulled in as a dependency by one of the dependencies that are currently listed).

**Comment by HemangChothani** [comment]
@simonvanderveldt Yes, as you have said `request` is installed by `google-resumable-media`,so don't want to make it redundant , `google-api-core` is also installed by the other dependency.

**Comment by simonvanderveldt** [comment]
> @simonvanderveldt Yes, as you have said `request` is installed by `google-resumable-media`,so don't want to make it redundant , `google-api-core` is also installed by the other dependency.

AFAIK That's not how `install_requires` works/is meant to be used. If a project uses a dependency directly it should be listed in its `install_requires`.

**Comment by HemangChothani** [comment]
>> AFAIK That's not how `install_requires` works/is meant to be used. If a project uses a dependency directly it should be listed in its `install_requires`.

I don't think there is any need to  mention `requests` in dependencies because if we follows, then there will be a bunch of redundant dependencies need to mention in the file .
@frankyn @tseaver could you please share your view?

**Comment by frankyn** [comment]
@andrewsg can you take a look at this question when you have a moment?

**Comment by tseaver** [comment]
Outside of tests, all use of the `requests` module is in docstrings (i.e., for clarity).  We do not need to mention it in `install_requires` for testing-only usage.

Note that [`google-resumable-media` only has an `extras_require` for `requests`](https://github.com/googleapis/google-resumable-media-python/blob/1da21840b4888ce4dcaba454a66ef1b4e86578c1/setup.py#L31-L35).  That is by design, with the intention that another transport might be added in the future.

**Comment by andrewsg** [comment]
It looks like there's exactly one non-test file that uses requests after all, google/cloud/storage/batch.py. Given that, we should add it to direct dependencies after all. I assume it didn't show up in our system testing because, as previously mentioned, dependencies were pulling requests in in both customer and test environments, so this is more of a formality.
