### ISSUE TITLE
Possible Connection Pool Issue with Multi-Processing

### ISSUE THREAD

**Issue by william-silversmith** [googleapis/python-storage#486]
Hi!

I have been investigating odd behavior in my own library (https://github.com/seung-lab/cloud-volume/pull/487). I am using threading and process pools to perform a high speed download of many files. However, when using the process pool, I get errors: 

```
HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token
(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1c5baebb0>: 
Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```

At first I thought it might be too many files open. I raised the ulimit tremendously but no dice. I tried executing it against cached files on the local system and it worked beautifully. That should rule out the file descriptors.

My next assumption was that this was some kind of rate limitation by GCS. This did not pan out as manipulating the number of threads on a single process or running parallel versions of the script in single process mode using bash did not trigger the problem.

This made me suspect that, similar to my own code that has a connection pools in it, that there might need to be cached connection pools or other data that must be cleared immediately after forking. For my own code, I call (my own)`reset_connection_pools()` on the first line after being called by the process pool as similar problems of a larger magnitude developed without it.

Does this sound reasonable? If so, I've looked around both python-storage, resumable media, urllib3, and requests and it wasn't obvious to me what the right way to do that would be.

My use case is made complicated by the requirement that I fetch a metadata file from GCS before executing the parallel process, so some pool somewhere is getting used most likely.

Thanks for your help!

**Comment by andrewsg** [comment]
Hi, thanks for your report!

Under the hood we use requests, and through that urllib3, for all of our connection handling. I'm not familiar with this sort of error stemming from connection pool issues. Can you describe the control flow of your program that might result in a connection pool-related issue here? Are you forking while you have calls ongoing or something like that? Normally I imagine forking happening before any connections begin, which should avoid any connection pool issues as the pool will be empty.

The connection pool itself is of type urllib3.HTTPConnectionPool, but because we delegate pool work to requests I am not personally familiar with how to access that object to modify or reset it.

**Comment by william-silversmith** [comment]
So we request a metadata file that describes our dataset, then we download images in bulk form the dataset. I suspect that the small number of connections made stick around inside the pool after the fork. I'll look more closely at the urllib3 documentation.

**Comment by tseaver** [comment]
@william-silversmith Are you re-using the `storage.Client` after the fork?  One quick workaround to try would be to have the child processes all instantiate their own `Client` instances post-fork.

**Comment by frankyn** [comment]
No follow-up closing out given no response. Please reopen if this is still an issue.
