### ISSUE TITLE
Let's use f-strings instead of .format() to increase readability of documentation

### ISSUE THREAD

**Issue by zabop** [googleapis/python-storage#785]
Functions in this repo appear in the official documentation. All of them I've seen so far uses the `.format()` method of string processing, instead of the much more readable f-strings. I am able to change all `.format()`s to f-strings if this is accepted as a better solution.

**Comment by Breathtender** [comment]
Hey @zabop, thanks for bringing this forward. We had been using `.format` because up until very recently we had still been supporting python2.7 with our libraries, but we recently phased out that support, and so I think this should be a good change to make. Appreciate you taking the initiative on it.
Once you have the PR ready feel free to link it with this issue and I'll give it a review.
Thanks!

**Comment by zabop** [comment]
Hey @Breathtender, thank you for the reply! I just made the PR.
