### ISSUE TITLE
Blob prefixes not available until you iterate the files

### ISSUE THREAD

**Issue by eavonius** [googleapis/python-storage#863]
#### Environment details

  - OS type and version: Windows 10
  - Python version: 3.9.13
  - pip version: 22.0.4
  - `google-cloud-storage` version: 2.5.0

#### Steps to reproduce

  1. Download the [sample code for listing files with a prefix](https://github.com/googleapis/python-storage/blob/282e3b605e62c4f8d93debff20d40afbf2e718f5/samples/snippets/storage_list_files_with_prefix.py).
  2. Comment out the lines 56-58 that print the names of each blob.
  3. Create a google cloud storage bucket with a subfolder, and a file within that subfolder.
  4. Run the sample where it specifies the subfolder as the prefix with slash at the end (as shown) and the delimiter of `'/'`.
  5. Nothing is displayed (the prefixes are empty).
  6. Un-comment the lines that print the names of each blob.
  7. Run it again.
  8. The prefixes are displayed.

It appears you cannot list the prefixes unless you iterate the files first. This seems strange. 

If it's intended, maybe this library should pre-iterate the list so this doesn't happen? Or at least document that this is expected?

**Comment by cojenco** [comment]
Hi eavonius, thank you for the question. You are right about the iterator has to be called first in order to access the list of prefixes. This is intended, as `list_blobs` operation returns an iterator, and the rpc is done with a response back only when you iterate through the [iterator](https://googleapis.dev/python/google-api-core/latest/page_iterator.html)

Another way that works too:
```
blobs = storage_client.list_blobs(bucket_name, prefix=prefix, delimiter=delimiter)

list(blobs)
print(blobs.prefixes)
```

I agree this could stand to be clarified in the documentation. I'll update the official documentation and sample notes.

**Comment by eavonius** [comment]
@cojenco thanks, makes sense to me. Yep a little note in the documentation would go a long way. Was very confusing at first. Thanks for the help!
