### ISSUE TITLE
List folders without scanning blobs

### ISSUE THREAD

**Issue by devdems** [googleapis/python-storage#886]
Is it possible to get the list of all folders in a bucket, even if they are "imaginary" objects without scanning all the blobs?

list_blobs function scans all blobs regardless if you put a prefix or not.

The use-case is a bucket with millions of blobs where only folders need to be returned.

**Comment by andrewsg** [comment]
At first glance I don't believe there is any way to do this on Storage because, unlike a filesystem on a local drive, in Storage folders aren't themselves objects - it's only a useful way to describe blob names with "/" in them. Without looking at the blobs it's impossible to tell which names include a "/" in them and what they are. I will ask team members and see if they have any suggestions.

**Comment by andrewsg** [comment]
Interestingly, it looks like there is a way to do this in the API; however, _regrettably, it is not currently supported in the client libraries_.

In an Objects: List response there is the `prefixes` response field which will be populated when there is a `delimiter` parameter specified. This will return values a bit like `ls` would.

For example, the following curl command:
`curl -X GET 'https://storage.googleapis.com/storage/v1/b/my-bucket/o?delimiter=%2F&fields=prefixes' -H "authorization: Bearer $(gcloud auth print-access-token)"`

would receive a response like this:
{
    "prefixes": [
        "b/",
        "object/",
        "xyz/"
    ]
}

This will only show the "folders" at the top level. To drill down, add `&prefix=b/` to the url to get, for instance, all further "folders" starting with "b/".

We don't yet support this behavior in the client libraries, and as you can see it's a touch clunky to do with the JSON API, but please feel free to file a feature request here if you think it would be useful.
